# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'
        cache: maven

    - name: Build with Maven
      run: mvn -B package -Dtest=RunTests --file pom.xml

    - name: publish html reports
      run: |
        ls -lah target/cucumber-html-reports/cucumber-html-reports
        mv target/cucumber-html-reports/cucumber-html-reports/ cucumber-html-reports/
        cd cucumber-html-reports && ls -lah
        mv overview-features.html index.html
        git config --global user.email "github-bot@github.com"
        git config --global user.name "github-bot@github.com"
        git checkout -b gh-pages
        git add .
        git commit -m "update reports"
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}